@API_URL_LINKS =  http://localhost:3000/links

### GET LINKS
GET {{API_URL_LINKS}} 

### GET LINKS BY ID
GET {{API_URL_LINKS}}/7

### POST LINKS
POST {{API_URL_LINKS}}
Content-Type: application/json

{
  "linkName": "Las mejores apps para pasar el tiempo",
  "description": "",
  "link": "https://www.youtube.com/watch?v=d1w429W3XcQ"
}

### DELETE LINKS BY ID
DELETE {{API_URL_LINKS}}/8

### UPDATE LINKS BY ID
PUT {{API_URL_LINKS}}/8
Content-Type: application/json

{
  "linkName": "NestJs vs NodeJs",
  "description": "Una comparativa entre estas dos herrameintas backend",
  "link": "https://www.youtube.com/watch?v=dqw429WgXcQ"
}
